// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ufrSet.Data;

#nullable disable

namespace ufrSet.Migrations
{
    [DbContext(typeof(ufrSetContext))]
    [Migration("20221117122328_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ufrSet.Models.Administration", b =>
                {
                    b.Property<string>("matricule")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("matricule");

                    b.ToTable("Administration");
                });

            modelBuilder.Entity("ufrSet.Models.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UfrId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UfrId");

                    b.ToTable("Departement");
                });

            modelBuilder.Entity("ufrSet.Models.Filiere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DepartementId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId");

                    b.ToTable("Filiere");
                });

            modelBuilder.Entity("ufrSet.Models.Pers", b =>
                {
                    b.Property<string>("matricule")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("matricule");

                    b.ToTable("Pers");
                });

            modelBuilder.Entity("ufrSet.Models.Ufr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ufr");
                });

            modelBuilder.Entity("ufrSet.Models.Departement", b =>
                {
                    b.HasOne("ufrSet.Models.Ufr", null)
                        .WithMany("departements")
                        .HasForeignKey("UfrId");
                });

            modelBuilder.Entity("ufrSet.Models.Filiere", b =>
                {
                    b.HasOne("ufrSet.Models.Departement", null)
                        .WithMany("filieres")
                        .HasForeignKey("DepartementId");
                });

            modelBuilder.Entity("ufrSet.Models.Departement", b =>
                {
                    b.Navigation("filieres");
                });

            modelBuilder.Entity("ufrSet.Models.Ufr", b =>
                {
                    b.Navigation("departements");
                });
#pragma warning restore 612, 618
        }
    }
}
